import { ErrorNode } from "antlr4ts/tree/ErrorNode";
import { ParseTree } from "antlr4ts/tree/ParseTree";
import { RuleNode } from "antlr4ts/tree/RuleNode";
import { TerminalNode } from "antlr4ts/tree/TerminalNode";
import { CompilationUnitContext, TargetDefContext, SourceFilenameContext, TargetDataLayoutContext, TargetTripleContext, TopLevelEntityContext, ModuleAsmContext, TypeDefContext, ComdatDefContext, GlobalDeclContext, GlobalDefContext, IndirectSymbolDefContext, FuncDeclContext, FuncDefContext, AttrGroupDefContext, NamedMetadataDefContext, MetadataDefContext, UseListOrderContext, UseListOrderBBContext, FuncHeaderContext, IndirectSymbolContext, CallingConvContext, CallingConvIntContext, FuncHdrFieldContext, GcContext, PrefixContext, PrologueContext, PersonalityContext, ReturnAttributeContext, FuncBodyContext, BasicBlockContext, InstructionContext, TerminatorContext, LocalDefTermContext, ValueTerminatorContext, RetTermContext, BrTermContext, CondBrTermContext, SwitchTermContext, IndirectBrTermContext, ResumeTermContext, CatchRetTermContext, CleanupRetTermContext, UnreachableTermContext, InvokeTermContext, CallBrTermContext, CatchSwitchTermContext, LabelContext, CaseContext, UnwindTargetContext, HandlersContext, MetadataNodeContext, DiExpressionContext, DiExpressionFieldContext, GlobalFieldContext, SectionContext, ComdatContext, PartitionContext, ConstantContext, BoolConstContext, IntConstContext, FloatConstContext, NullConstContext, NoneConstContext, StructConstContext, ArrayConstContext, VectorConstContext, ZeroInitializerConstContext, UndefConstContext, PoisonConstContext, BlockAddressConstContext, DsoLocalEquivalentConstContext, NoCFIConstContext, ConstantExprContext, TypeConstContext, MetadataAttachmentContext, MdNodeContext, MdTupleContext, MetadataContext, DiArgListContext, TypeValueContext, ValueContext, InlineAsmContext, MdStringContext, MdFieldOrIntContext, DiSPFlagContext, FuncAttributeContext, TypeContext, ParamsContext, ParamContext, ParamAttributeContext, AttrStringContext, AttrPairContext, AlignContext, AlignPairContext, AlignStackContext, AlignStackPairContext, AllocKindContext, AllocSizeContext, UnwindTableContext, VectorScaleRangeContext, ByRefAttrContext, ByvalContext, DereferenceableContext, ElementTypeContext, InAllocaContext, ParamAttrContext, PreallocatedContext, StructRetAttrContext, FirstClassTypeContext, ConcreteTypeContext, IntTypeContext, FloatTypeContext, PointerTypeContext, VectorTypeContext, LabelTypeContext, ArrayTypeContext, StructTypeContext, NamedTypeContext, MmxTypeContext, TokenTypeContext, OpaquePointerTypeContext, AddrSpaceContext, ThreadLocalContext, MetadataTypeContext, BitCastExprContext, GetElementPtrExprContext, GepIndexContext, AddrSpaceCastExprContext, IntToPtrExprContext, ICmpExprContext, FCmpExprContext, SelectExprContext, TruncExprContext, ZExtExprContext, SExtExprContext, FpTruncExprContext, FpExtExprContext, FpToUiExprContext, FpToSiExprContext, UiToFpExprContext, SiToFpExprContext, PtrToIntExprContext, ExtractElementExprContext, InsertElementExprContext, ShuffleVectorExprContext, ShlExprContext, LShrExprContext, AShrExprContext, AndExprContext, OrExprContext, XorExprContext, AddExprContext, SubExprContext, MulExprContext, FNegExprContext, LocalDefInstContext, ValueInstructionContext, StoreInstContext, SyncScopeContext, FenceInstContext, FNegInstContext, AddInstContext, FAddInstContext, SubInstContext, FSubInstContext, MulInstContext, FMulInstContext, UDivInstContext, SDivInstContext, FDivInstContext, URemInstContext, SRemInstContext, FRemInstContext, ShlInstContext, LShrInstContext, AShrInstContext, AndInstContext, OrInstContext, XorInstContext, ExtractElementInstContext, InsertElementInstContext, ShuffleVectorInstContext, ExtractValueInstContext, InsertValueInstContext, AllocaInstContext, LoadInstContext, CmpXchgInstContext, AtomicRMWInstContext, GetElementPtrInstContext, TruncInstContext, ZExtInstContext, SExtInstContext, FpTruncInstContext, FpExtInstContext, FpToUiInstContext, FpToSiInstContext, UiToFpInstContext, SiToFpInstContext, PtrToIntInstContext, IntToPtrInstContext, BitCastInstContext, AddrSpaceCastInstContext, ICmpInstContext, FCmpInstContext, PhiInstContext, SelectInstContext, FreezeInstContext, CallInstContext, VaargInstContext, LandingPadInstContext, CatchPadInstContext, CleanupPadInstContext, IncContext, OperandBundleContext, ClauseContext, ArgsContext, ArgContext, ExceptionArgContext, ExceptionPadContext, ExternalLinkageContext, InternalLinkageContext, LinkageContext, PreemptionContext, VisibilityContext, DllStorageClassContext, TlsModelContext, UnnamedAddrContext, ExternallyInitializedContext, ImmutableContext, FuncAttrContext, DistinctContext, InBoundsContext, ReturnAttrContext, OverflowFlagContext, IPredContext, FPredContext, AtomicOrderingContext, CallingConvEnumContext, FastMathFlagContext, AtomicOpContext, FloatKindContext, SpecializedMDNodeContext, DiBasicTypeContext, DiCommonBlockContext, DiCompileUnitContext, DiCompositeTypeContext, DiCompositeTypeFieldContext, DiDerivedTypeContext, DiDerivedTypeFieldContext, DiEnumeratorContext, DiEnumeratorFieldContext, DiFileContext, DiFileFieldContext, DiGlobalVariableContext, DiGlobalVariableFieldContext, DiGlobalVariableExpressionContext, DiGlobalVariableExpressionFieldContext, DiImportedEntityContext, DiImportedEntityFieldContext, DiLabelContext, DiLabelFieldContext, DiLexicalBlockContext, DiLexicalBlockFieldContext, DiLexicalBlockFileContext, DiLexicalBlockFileFieldContext, DiLocalVariableContext, DiLocalVariableFieldContext, DiLocationContext, DiLocationFieldContext, DiMacroContext, DiMacroFieldContext, DiMacroFileContext, DiMacroFileFieldContext, DiModuleContext, DiModuleFieldContext, DiNamespaceContext, DiNamespaceFieldContext, DiObjCPropertyContext, DiObjCPropertyFieldContext, DiStringTypeContext, DiStringTypeFieldContext, DiSubprogramContext, DiSubprogramFieldContext, DiSubrangeContext, DiSubrangeFieldContext, DiSubroutineTypeContext, DiTemplateTypeParameterContext, DiTemplateValueParameterContext, GenericDiNodeContext, DiTemplateTypeParameterFieldContext, DiCompileUnitFieldContext, DiCommonBlockFieldContext, DiBasicTypeFieldContext, GenericDINodeFieldContext, TagFieldContext, HeaderFieldContext, OperandsFieldContext, DiTemplateValueParameterFieldContext, NameFieldContext, TypeFieldContext, DefaultedFieldContext, ValueFieldContext, MdFieldContext, DiSubroutineTypeFieldContext, FlagsFieldContext, DiFlagsContext, CcFieldContext, AlignFieldContext, AllocatedFieldContext, AnnotationsFieldContext, ArgFieldContext, AssociatedFieldContext, AttributesFieldContext, BaseTypeFieldContext, ChecksumFieldContext, ChecksumkindFieldContext, ColumnFieldContext, ConfigMacrosFieldContext, ContainingTypeFieldContext, CountFieldContext, DebugInfoForProfilingFieldContext, DeclarationFieldContext, DirectoryFieldContext, DiscriminatorFieldContext, DataLocationFieldContext, DiscriminatorIntFieldContext, DwarfAddressSpaceFieldContext, DwoIdFieldContext, ElementsFieldContext, EmissionKindFieldContext, EncodingFieldContext, EntityFieldContext, EnumsFieldContext, ExportSymbolsFieldContext, ExprFieldContext, ExtraDataFieldContext, FileFieldContext, FilenameFieldContext, FlagsStringFieldContext, GetterFieldContext, GlobalsFieldContext, IdentifierFieldContext, ImportsFieldContext, IncludePathFieldContext, InlinedAtFieldContext, IsDeclFieldContext, IsDefinitionFieldContext, IsImplicitCodeFieldContext, IsLocalFieldContext, IsOptimizedFieldContext, IsUnsignedFieldContext, ApiNotesFieldContext, LanguageFieldContext, LineFieldContext, LinkageNameFieldContext, LowerBoundFieldContext, MacrosFieldContext, NameTableKindFieldContext, NodesFieldContext, OffsetFieldContext, ProducerFieldContext, RangesBaseAddressFieldContext, RankFieldContext, RetainedNodesFieldContext, RetainedTypesFieldContext, RuntimeLangFieldContext, RuntimeVersionFieldContext, ScopeFieldContext, ScopeLineFieldContext, SdkFieldContext, SetterFieldContext, SizeFieldContext, SourceFieldContext, SpFlagsFieldContext, SplitDebugFilenameFieldContext, SplitDebugInliningFieldContext, StrideFieldContext, StringLengthFieldContext, StringLengthExpressionFieldContext, StringLocationExpressionFieldContext, SysrootFieldContext, TargetFuncNameFieldContext, TemplateParamsFieldContext, ThisAdjustmentFieldContext, ThrownTypesFieldContext, TypeMacinfoFieldContext, TypesFieldContext, UnitFieldContext, UpperBoundFieldContext, ValueIntFieldContext, ValueStringFieldContext, VarFieldContext, VirtualIndexFieldContext, VirtualityFieldContext, VtableHolderFieldContext, VoidTypeContext, OpaqueTypeContext } from "../llvmir/LLVMIRParser";
import { LLVMIRVisitor } from "../llvmir/LLVMIRVisitor";

// 使用正则表达式 \?: \(\(ctx: ([a-zA-Z]+)\) => void\) \| undefined;
// 替换为 (ctx: $1): void { this.visitChildren(ctx); }
export class LLVMIRBaseVisitor implements LLVMIRVisitor<void> {
  
  visitCompilationUnit(ctx: CompilationUnitContext): void { this.visitChildren(ctx); }
  visitTopLevelEntity(ctx: TopLevelEntityContext): void { this.visitChildren(ctx); }
  visitTypeDef(ctx: TypeDefContext): void { this.visitChildren(ctx); }
  visitGlobalDecl(ctx: GlobalDeclContext): void { this.visitChildren(ctx); }
  visitGlobalDef(ctx: GlobalDefContext): void { this.visitChildren(ctx); }
  visitIndirectSymbolDef(ctx: IndirectSymbolDefContext): void { this.visitChildren(ctx); }
  visitFuncDecl(ctx: FuncDeclContext): void { this.visitChildren(ctx); }
  visitFuncDef(ctx: FuncDefContext): void { this.visitChildren(ctx); }
  visitFuncHeader(ctx: FuncHeaderContext): void { this.visitChildren(ctx); }
  visitIndirectSymbol(ctx: IndirectSymbolContext): void { this.visitChildren(ctx); }
  visitFuncBody(ctx: FuncBodyContext): void { this.visitChildren(ctx); }
  visitBasicBlock(ctx: BasicBlockContext): void { this.visitChildren(ctx); }
  visitInstruction(ctx: InstructionContext): void { this.visitChildren(ctx); }
  visitTerminator(ctx: TerminatorContext): void { this.visitChildren(ctx); }
  visitLocalDefTerm(ctx: LocalDefTermContext): void { this.visitChildren(ctx); }
  visitValueTerminator(ctx: ValueTerminatorContext): void { this.visitChildren(ctx); }
  visitRetTerm(ctx: RetTermContext): void { this.visitChildren(ctx); }
  visitBrTerm(ctx: BrTermContext): void { this.visitChildren(ctx); }
  visitCondBrTerm(ctx: CondBrTermContext): void { this.visitChildren(ctx); }
  visitSwitchTerm(ctx: SwitchTermContext): void { this.visitChildren(ctx); }
  visitIndirectBrTerm(ctx: IndirectBrTermContext): void { this.visitChildren(ctx); }
  visitResumeTerm(ctx: ResumeTermContext): void { this.visitChildren(ctx); }
  visitCatchRetTerm(ctx: CatchRetTermContext): void { this.visitChildren(ctx); }
  visitCleanupRetTerm(ctx: CleanupRetTermContext): void { this.visitChildren(ctx); }
  visitUnreachableTerm(ctx: UnreachableTermContext): void { this.visitChildren(ctx); }
  visitInvokeTerm(ctx: InvokeTermContext): void { this.visitChildren(ctx); }
  visitCallBrTerm(ctx: CallBrTermContext): void { this.visitChildren(ctx); }
  visitCatchSwitchTerm(ctx: CatchSwitchTermContext): void { this.visitChildren(ctx); }
  visitLabel(ctx: LabelContext): void { this.visitChildren(ctx); }
  visitCase(ctx: CaseContext): void { this.visitChildren(ctx); }
  visitType(ctx: TypeContext): void { this.visitChildren(ctx); }
  visitParams(ctx: ParamsContext): void { this.visitChildren(ctx); }
  visitParam(ctx: ParamContext): void { this.visitChildren(ctx); }
  visitTypeValue(ctx: TypeValueContext): void { this.visitChildren(ctx); }
  visitValue(ctx: ValueContext): void { this.visitChildren(ctx); }
  // type
  visitFirstClassType(ctx: FirstClassTypeContext): void { this.visitChildren(ctx); }
  visitConcreteType(ctx: ConcreteTypeContext): void { this.visitChildren(ctx); }
  visitIntType(ctx: IntTypeContext): void { this.visitChildren(ctx); }
  visitFloatType(ctx: FloatTypeContext): void { this.visitChildren(ctx); }
  visitPointerType(ctx: PointerTypeContext): void { this.visitChildren(ctx); }
  visitVectorType(ctx: VectorTypeContext): void { this.visitChildren(ctx); }
  visitLabelType(ctx: LabelTypeContext): void { this.visitChildren(ctx); }
  visitArrayType(ctx: ArrayTypeContext): void { this.visitChildren(ctx); }
  visitStructType(ctx: StructTypeContext): void { this.visitChildren(ctx); }
  visitNamedType(ctx: NamedTypeContext): void { this.visitChildren(ctx); }
  visitMmxType(ctx: MmxTypeContext): void { this.visitChildren(ctx); }
  visitTokenType(ctx: TokenTypeContext): void { this.visitChildren(ctx); }
  visitOpaquePointerType(ctx: OpaquePointerTypeContext): void { this.visitChildren(ctx); }
  visitVoidType(ctx: VoidTypeContext): void { this.visitChildren(ctx); }
  visitOpaqueType(ctx: OpaqueTypeContext): void { this.visitChildren(ctx); }
  // constant
  visitConstant(ctx: ConstantContext): void { this.visitChildren(ctx); }
  visitBoolConst(ctx: BoolConstContext): void { this.visitChildren(ctx); }
  visitIntConst(ctx: IntConstContext): void { this.visitChildren(ctx); }
  visitFloatConst(ctx: FloatConstContext): void { this.visitChildren(ctx); }
  visitNullConst(ctx: NullConstContext): void { this.visitChildren(ctx); }
  visitNoneConst(ctx: NoneConstContext): void { this.visitChildren(ctx); }
  visitStructConst(ctx: StructConstContext): void { this.visitChildren(ctx); }
  visitArrayConst(ctx: ArrayConstContext): void { this.visitChildren(ctx); }
  visitVectorConst(ctx: VectorConstContext): void { this.visitChildren(ctx); }
  visitZeroInitializerConst(ctx: ZeroInitializerConstContext): void { this.visitChildren(ctx); }
  visitUndefConst(ctx: UndefConstContext): void { this.visitChildren(ctx); }
  visitPoisonConst(ctx: PoisonConstContext): void { this.visitChildren(ctx); }
  visitBlockAddressConst(ctx: BlockAddressConstContext): void { this.visitChildren(ctx); }
  visitDsoLocalEquivalentConst(ctx: DsoLocalEquivalentConstContext): void { this.visitChildren(ctx); }
  visitNoCFIConst(ctx: NoCFIConstContext): void { this.visitChildren(ctx); }
  visitTypeConst(ctx: TypeConstContext): void { this.visitChildren(ctx); }
  
  // expr
  visitConstantExpr(ctx: ConstantExprContext): void { this.visitChildren(ctx); }
  visitBitCastExpr(ctx: BitCastExprContext): void { this.visitChildren(ctx); }
  visitGetElementPtrExpr(ctx: GetElementPtrExprContext): void { this.visitChildren(ctx); }
  visitGepIndex(ctx: GepIndexContext): void { this.visitChildren(ctx); }
  visitAddrSpaceCastExpr(ctx: AddrSpaceCastExprContext): void { this.visitChildren(ctx); }
  visitIntToPtrExpr(ctx: IntToPtrExprContext): void { this.visitChildren(ctx); }
  visitICmpExpr(ctx: ICmpExprContext): void { this.visitChildren(ctx); }
  visitFCmpExpr(ctx: FCmpExprContext): void { this.visitChildren(ctx); }
  visitSelectExpr(ctx: SelectExprContext): void { this.visitChildren(ctx); }
  visitTruncExpr(ctx: TruncExprContext): void { this.visitChildren(ctx); }
  visitZExtExpr(ctx: ZExtExprContext): void { this.visitChildren(ctx); }
  visitSExtExpr(ctx: SExtExprContext): void { this.visitChildren(ctx); }
  visitFpTruncExpr(ctx: FpTruncExprContext): void { this.visitChildren(ctx); }
  visitFpExtExpr(ctx: FpExtExprContext): void { this.visitChildren(ctx); }
  visitFpToUiExpr(ctx: FpToUiExprContext): void { this.visitChildren(ctx); }
  visitFpToSiExpr(ctx: FpToSiExprContext): void { this.visitChildren(ctx); }
  visitUiToFpExpr(ctx: UiToFpExprContext): void { this.visitChildren(ctx); }
  visitSiToFpExpr(ctx: SiToFpExprContext): void { this.visitChildren(ctx); }
  visitPtrToIntExpr(ctx: PtrToIntExprContext): void { this.visitChildren(ctx); }
  visitExtractElementExpr(ctx: ExtractElementExprContext): void { this.visitChildren(ctx); }
  visitInsertElementExpr(ctx: InsertElementExprContext): void { this.visitChildren(ctx); }
  visitShuffleVectorExpr(ctx: ShuffleVectorExprContext): void { this.visitChildren(ctx); }
  visitShlExpr(ctx: ShlExprContext): void { this.visitChildren(ctx); }
  visitLShrExpr(ctx: LShrExprContext): void { this.visitChildren(ctx); }
  visitAShrExpr(ctx: AShrExprContext): void { this.visitChildren(ctx); }
  visitAndExpr(ctx: AndExprContext): void { this.visitChildren(ctx); }
  visitOrExpr(ctx: OrExprContext): void { this.visitChildren(ctx); }
  visitXorExpr(ctx: XorExprContext): void { this.visitChildren(ctx); }
  visitAddExpr(ctx: AddExprContext): void { this.visitChildren(ctx); }
  visitSubExpr(ctx: SubExprContext): void { this.visitChildren(ctx); }
  visitMulExpr(ctx: MulExprContext): void { this.visitChildren(ctx); }
  visitFNegExpr(ctx: FNegExprContext): void { this.visitChildren(ctx); }
  // inst
  visitFenceInst(ctx: FenceInstContext): void { this.visitChildren(ctx); }
  visitFNegInst(ctx: FNegInstContext): void { this.visitChildren(ctx); }
  visitAddInst(ctx: AddInstContext): void { this.visitChildren(ctx); }
  visitFAddInst(ctx: FAddInstContext): void { this.visitChildren(ctx); }
  visitSubInst(ctx: SubInstContext): void { this.visitChildren(ctx); }
  visitFSubInst(ctx: FSubInstContext): void { this.visitChildren(ctx); }
  visitMulInst(ctx: MulInstContext): void { this.visitChildren(ctx); }
  visitFMulInst(ctx: FMulInstContext): void { this.visitChildren(ctx); }
  visitUDivInst(ctx: UDivInstContext): void { this.visitChildren(ctx); }
  visitSDivInst(ctx: SDivInstContext): void { this.visitChildren(ctx); }
  visitFDivInst(ctx: FDivInstContext): void { this.visitChildren(ctx); }
  visitURemInst(ctx: URemInstContext): void { this.visitChildren(ctx); }
  visitSRemInst(ctx: SRemInstContext): void { this.visitChildren(ctx); }
  visitFRemInst(ctx: FRemInstContext): void { this.visitChildren(ctx); }
  visitShlInst(ctx: ShlInstContext): void { this.visitChildren(ctx); }
  visitLShrInst(ctx: LShrInstContext): void { this.visitChildren(ctx); }
  visitAShrInst(ctx: AShrInstContext): void { this.visitChildren(ctx); }
  visitAndInst(ctx: AndInstContext): void { this.visitChildren(ctx); }
  visitOrInst(ctx: OrInstContext): void { this.visitChildren(ctx); }
  visitXorInst(ctx: XorInstContext): void { this.visitChildren(ctx); }
  visitExtractElementInst(ctx: ExtractElementInstContext): void { this.visitChildren(ctx); }
  visitInsertElementInst(ctx: InsertElementInstContext): void { this.visitChildren(ctx); }
  visitShuffleVectorInst(ctx: ShuffleVectorInstContext): void { this.visitChildren(ctx); }
  visitExtractValueInst(ctx: ExtractValueInstContext): void { this.visitChildren(ctx); }
  visitInsertValueInst(ctx: InsertValueInstContext): void { this.visitChildren(ctx); }
  visitAllocaInst(ctx: AllocaInstContext): void { this.visitChildren(ctx); }
  visitLoadInst(ctx: LoadInstContext): void { this.visitChildren(ctx); }
  visitCmpXchgInst(ctx: CmpXchgInstContext): void { this.visitChildren(ctx); }
  visitAtomicRMWInst(ctx: AtomicRMWInstContext): void { this.visitChildren(ctx); }
  visitGetElementPtrInst(ctx: GetElementPtrInstContext): void { this.visitChildren(ctx); }
  visitTruncInst(ctx: TruncInstContext): void { this.visitChildren(ctx); }
  visitZExtInst(ctx: ZExtInstContext): void { this.visitChildren(ctx); }
  visitSExtInst(ctx: SExtInstContext): void { this.visitChildren(ctx); }
  visitFpTruncInst(ctx: FpTruncInstContext): void { this.visitChildren(ctx); }
  visitFpExtInst(ctx: FpExtInstContext): void { this.visitChildren(ctx); }
  visitFpToUiInst(ctx: FpToUiInstContext): void { this.visitChildren(ctx); }
  visitFpToSiInst(ctx: FpToSiInstContext): void { this.visitChildren(ctx); }
  visitUiToFpInst(ctx: UiToFpInstContext): void { this.visitChildren(ctx); }
  visitSiToFpInst(ctx: SiToFpInstContext): void { this.visitChildren(ctx); }
  visitPtrToIntInst(ctx: PtrToIntInstContext): void { this.visitChildren(ctx); }
  visitIntToPtrInst(ctx: IntToPtrInstContext): void { this.visitChildren(ctx); }
  visitBitCastInst(ctx: BitCastInstContext): void { this.visitChildren(ctx); }
  visitAddrSpaceCastInst(ctx: AddrSpaceCastInstContext): void { this.visitChildren(ctx); }
  visitICmpInst(ctx: ICmpInstContext): void { this.visitChildren(ctx); }
  visitFCmpInst(ctx: FCmpInstContext): void { this.visitChildren(ctx); }
  visitPhiInst(ctx: PhiInstContext): void { this.visitChildren(ctx); }
  visitSelectInst(ctx: SelectInstContext): void { this.visitChildren(ctx); }
  visitFreezeInst(ctx: FreezeInstContext): void { this.visitChildren(ctx); }
  visitCallInst(ctx: CallInstContext): void { this.visitChildren(ctx); }
  visitVaargInst(ctx: VaargInstContext): void { this.visitChildren(ctx); }
  visitLandingPadInst(ctx: LandingPadInstContext): void { this.visitChildren(ctx); }
  visitCatchPadInst(ctx: CatchPadInstContext): void { this.visitChildren(ctx); }
  visitCleanupPadInst(ctx: CleanupPadInstContext): void { this.visitChildren(ctx); }
  visitStoreInst(ctx: StoreInstContext): void { this.visitChildren(ctx); }
  visitLocalDefInst(ctx: LocalDefInstContext): void { this.visitChildren(ctx); }

  visitTargetDef(ctx: TargetDefContext): void { this.visitChildren(ctx); }
  visitSourceFilename(ctx: SourceFilenameContext): void { this.visitChildren(ctx); }
  visitTargetDataLayout(ctx: TargetDataLayoutContext): void { this.visitChildren(ctx); }
  visitTargetTriple(ctx: TargetTripleContext): void { this.visitChildren(ctx); }
  visitComdatDef(ctx: ComdatDefContext): void { this.visitChildren(ctx); }
  visitModuleAsm(ctx: ModuleAsmContext): void { this.visitChildren(ctx); }
  visitAttrGroupDef(ctx: AttrGroupDefContext): void { this.visitChildren(ctx); }
  visitNamedMetadataDef(ctx: NamedMetadataDefContext): void { this.visitChildren(ctx); }
  visitMetadataDef(ctx: MetadataDefContext): void { this.visitChildren(ctx); }
  visitUseListOrder(ctx: UseListOrderContext): void { this.visitChildren(ctx); }
  visitUseListOrderBB(ctx: UseListOrderBBContext): void { this.visitChildren(ctx); }
  visitCallingConv(ctx: CallingConvContext): void { this.visitChildren(ctx); }
  visitCallingConvInt(ctx: CallingConvIntContext): void { this.visitChildren(ctx); }
  visitFuncHdrField(ctx: FuncHdrFieldContext): void { this.visitChildren(ctx); }
  visitGc(ctx: GcContext): void { this.visitChildren(ctx); }
  visitPrefix(ctx: PrefixContext): void { this.visitChildren(ctx); }
  visitPrologue(ctx: PrologueContext): void { this.visitChildren(ctx); }
  visitPersonality(ctx: PersonalityContext): void { this.visitChildren(ctx); }
  visitReturnAttribute(ctx: ReturnAttributeContext): void { this.visitChildren(ctx); }
  visitUnwindTarget(ctx: UnwindTargetContext): void { this.visitChildren(ctx); }
  visitHandlers(ctx: HandlersContext): void { this.visitChildren(ctx); }
  visitMetadataNode(ctx: MetadataNodeContext): void { this.visitChildren(ctx); }
  visitDiExpression(ctx: DiExpressionContext): void { this.visitChildren(ctx); }
  visitDiExpressionField(ctx: DiExpressionFieldContext): void { this.visitChildren(ctx); }
  visitGlobalField(ctx: GlobalFieldContext): void { this.visitChildren(ctx); }
  visitSection(ctx: SectionContext): void { this.visitChildren(ctx); }
  visitComdat(ctx: ComdatContext): void { this.visitChildren(ctx); }
  visitPartition(ctx: PartitionContext): void { this.visitChildren(ctx); }
  visitMetadataAttachment(ctx: MetadataAttachmentContext): void { this.visitChildren(ctx); }
  visitMdNode(ctx: MdNodeContext): void { this.visitChildren(ctx); }
  visitMdTuple(ctx: MdTupleContext): void { this.visitChildren(ctx); }
  visitMetadata(ctx: MetadataContext): void { this.visitChildren(ctx); }
  visitDiArgList(ctx: DiArgListContext): void { this.visitChildren(ctx); }
  visitInlineAsm(ctx: InlineAsmContext): void { this.visitChildren(ctx); }
  visitMdString(ctx: MdStringContext): void { this.visitChildren(ctx); }
  visitMdFieldOrInt(ctx: MdFieldOrIntContext): void { this.visitChildren(ctx); }
  visitDiSPFlag(ctx: DiSPFlagContext): void { this.visitChildren(ctx); }
  visitFuncAttribute(ctx: FuncAttributeContext): void { this.visitChildren(ctx); }
  visitParamAttribute(ctx: ParamAttributeContext): void { this.visitChildren(ctx); }
  visitAttrString(ctx: AttrStringContext): void { this.visitChildren(ctx); }
  visitAttrPair(ctx: AttrPairContext): void { this.visitChildren(ctx); }
  visitAlign(ctx: AlignContext): void { this.visitChildren(ctx); }
  visitAlignPair(ctx: AlignPairContext): void { this.visitChildren(ctx); }
  visitAlignStack(ctx: AlignStackContext): void { this.visitChildren(ctx); }
  visitAlignStackPair(ctx: AlignStackPairContext): void { this.visitChildren(ctx); }
  visitAllocKind(ctx: AllocKindContext): void { this.visitChildren(ctx); }
  visitAllocSize(ctx: AllocSizeContext): void { this.visitChildren(ctx); }
  visitUnwindTable(ctx: UnwindTableContext): void { this.visitChildren(ctx); }
  visitVectorScaleRange(ctx: VectorScaleRangeContext): void { this.visitChildren(ctx); }
  visitByRefAttr(ctx: ByRefAttrContext): void { this.visitChildren(ctx); }
  visitByval(ctx: ByvalContext): void { this.visitChildren(ctx); }
  visitDereferenceable(ctx: DereferenceableContext): void { this.visitChildren(ctx); }
  visitElementType(ctx: ElementTypeContext): void { this.visitChildren(ctx); }
  visitInAlloca(ctx: InAllocaContext): void { this.visitChildren(ctx); }
  visitParamAttr(ctx: ParamAttrContext): void { this.visitChildren(ctx); }
  visitPreallocated(ctx: PreallocatedContext): void { this.visitChildren(ctx); }
  visitStructRetAttr(ctx: StructRetAttrContext): void { this.visitChildren(ctx); }
  visitAddrSpace(ctx: AddrSpaceContext): void { this.visitChildren(ctx); }
  visitThreadLocal(ctx: ThreadLocalContext): void { this.visitChildren(ctx); }
  visitMetadataType(ctx: MetadataTypeContext): void { this.visitChildren(ctx); }
  visitValueInstruction(ctx: ValueInstructionContext): void { this.visitChildren(ctx); }
  visitSyncScope(ctx: SyncScopeContext): void { this.visitChildren(ctx); }
  visitInc(ctx: IncContext): void { this.visitChildren(ctx); }
  visitOperandBundle(ctx: OperandBundleContext): void { this.visitChildren(ctx); }
  visitClause(ctx: ClauseContext): void { this.visitChildren(ctx); }
  visitArgs(ctx: ArgsContext): void { this.visitChildren(ctx); }
  visitArg(ctx: ArgContext): void { this.visitChildren(ctx); }
  visitExceptionArg(ctx: ExceptionArgContext): void { this.visitChildren(ctx); }
  visitExceptionPad(ctx: ExceptionPadContext): void { this.visitChildren(ctx); }
  visitExternalLinkage(ctx: ExternalLinkageContext): void { this.visitChildren(ctx); }
  visitInternalLinkage(ctx: InternalLinkageContext): void { this.visitChildren(ctx); }
  visitLinkage(ctx: LinkageContext): void { this.visitChildren(ctx); }
  visitPreemption(ctx: PreemptionContext): void { this.visitChildren(ctx); }
  visitVisibility(ctx: VisibilityContext): void { this.visitChildren(ctx); }
  visitDllStorageClass(ctx: DllStorageClassContext): void { this.visitChildren(ctx); }
  visitTlsModel(ctx: TlsModelContext): void { this.visitChildren(ctx); }
  visitUnnamedAddr(ctx: UnnamedAddrContext): void { this.visitChildren(ctx); }
  visitExternallyInitialized(ctx: ExternallyInitializedContext): void { this.visitChildren(ctx); }
  visitImmutable(ctx: ImmutableContext): void { this.visitChildren(ctx); }
  visitFuncAttr(ctx: FuncAttrContext): void { this.visitChildren(ctx); }
  visitDistinct(ctx: DistinctContext): void { this.visitChildren(ctx); }
  visitInBounds(ctx: InBoundsContext): void { this.visitChildren(ctx); }
  visitReturnAttr(ctx: ReturnAttrContext): void { this.visitChildren(ctx); }
  visitOverflowFlag(ctx: OverflowFlagContext): void { this.visitChildren(ctx); }
  visitIPred(ctx: IPredContext): void { this.visitChildren(ctx); }
  visitFPred(ctx: FPredContext): void { this.visitChildren(ctx); }
  visitAtomicOrdering(ctx: AtomicOrderingContext): void { this.visitChildren(ctx); }
  visitCallingConvEnum(ctx: CallingConvEnumContext): void { this.visitChildren(ctx); }
  visitFastMathFlag(ctx: FastMathFlagContext): void { this.visitChildren(ctx); }
  visitAtomicOp(ctx: AtomicOpContext): void { this.visitChildren(ctx); }
  visitFloatKind(ctx: FloatKindContext): void { this.visitChildren(ctx); }
  visitSpecializedMDNode(ctx: SpecializedMDNodeContext): void { this.visitChildren(ctx); }
  visitDiBasicType(ctx: DiBasicTypeContext): void { this.visitChildren(ctx); }
  visitDiCommonBlock(ctx: DiCommonBlockContext): void { this.visitChildren(ctx); }
  visitDiCompileUnit(ctx: DiCompileUnitContext): void { this.visitChildren(ctx); }
  visitDiCompositeType(ctx: DiCompositeTypeContext): void { this.visitChildren(ctx); }
  visitDiCompositeTypeField(ctx: DiCompositeTypeFieldContext): void { this.visitChildren(ctx); }
  visitDiDerivedType(ctx: DiDerivedTypeContext): void { this.visitChildren(ctx); }
  visitDiDerivedTypeField(ctx: DiDerivedTypeFieldContext): void { this.visitChildren(ctx); }
  visitDiEnumerator(ctx: DiEnumeratorContext): void { this.visitChildren(ctx); }
  visitDiEnumeratorField(ctx: DiEnumeratorFieldContext): void { this.visitChildren(ctx); }
  visitDiFile(ctx: DiFileContext): void { this.visitChildren(ctx); }
  visitDiFileField(ctx: DiFileFieldContext): void { this.visitChildren(ctx); }
  visitDiGlobalVariable(ctx: DiGlobalVariableContext): void { this.visitChildren(ctx); }
  visitDiGlobalVariableField(ctx: DiGlobalVariableFieldContext): void { this.visitChildren(ctx); }
  visitDiGlobalVariableExpression(ctx: DiGlobalVariableExpressionContext): void { this.visitChildren(ctx); }
  visitDiGlobalVariableExpressionField(ctx: DiGlobalVariableExpressionFieldContext): void { this.visitChildren(ctx); }
  visitDiImportedEntity(ctx: DiImportedEntityContext): void { this.visitChildren(ctx); }
  visitDiImportedEntityField(ctx: DiImportedEntityFieldContext): void { this.visitChildren(ctx); }
  visitDiLabel(ctx: DiLabelContext): void { this.visitChildren(ctx); }
  visitDiLabelField(ctx: DiLabelFieldContext): void { this.visitChildren(ctx); }
  visitDiLexicalBlock(ctx: DiLexicalBlockContext): void { this.visitChildren(ctx); }
  visitDiLexicalBlockField(ctx: DiLexicalBlockFieldContext): void { this.visitChildren(ctx); }
  visitDiLexicalBlockFile(ctx: DiLexicalBlockFileContext): void { this.visitChildren(ctx); }
  visitDiLexicalBlockFileField(ctx: DiLexicalBlockFileFieldContext): void { this.visitChildren(ctx); }
  visitDiLocalVariable(ctx: DiLocalVariableContext): void { this.visitChildren(ctx); }
  visitDiLocalVariableField(ctx: DiLocalVariableFieldContext): void { this.visitChildren(ctx); }
  visitDiLocation(ctx: DiLocationContext): void { this.visitChildren(ctx); }
  visitDiLocationField(ctx: DiLocationFieldContext): void { this.visitChildren(ctx); }
  visitDiMacro(ctx: DiMacroContext): void { this.visitChildren(ctx); }
  visitDiMacroField(ctx: DiMacroFieldContext): void { this.visitChildren(ctx); }
  visitDiMacroFile(ctx: DiMacroFileContext): void { this.visitChildren(ctx); }
  visitDiMacroFileField(ctx: DiMacroFileFieldContext): void { this.visitChildren(ctx); }
  visitDiModule(ctx: DiModuleContext): void { this.visitChildren(ctx); }
  visitDiModuleField(ctx: DiModuleFieldContext): void { this.visitChildren(ctx); }
  visitDiNamespace(ctx: DiNamespaceContext): void { this.visitChildren(ctx); }
  visitDiNamespaceField(ctx: DiNamespaceFieldContext): void { this.visitChildren(ctx); }
  visitDiObjCProperty(ctx: DiObjCPropertyContext): void { this.visitChildren(ctx); }
  visitDiObjCPropertyField(ctx: DiObjCPropertyFieldContext): void { this.visitChildren(ctx); }
  visitDiStringType(ctx: DiStringTypeContext): void { this.visitChildren(ctx); }
  visitDiStringTypeField(ctx: DiStringTypeFieldContext): void { this.visitChildren(ctx); }
  visitDiSubprogram(ctx: DiSubprogramContext): void { this.visitChildren(ctx); }
  visitDiSubprogramField(ctx: DiSubprogramFieldContext): void { this.visitChildren(ctx); }
  visitDiSubrange(ctx: DiSubrangeContext): void { this.visitChildren(ctx); }
  visitDiSubrangeField(ctx: DiSubrangeFieldContext): void { this.visitChildren(ctx); }
  visitDiSubroutineType(ctx: DiSubroutineTypeContext): void { this.visitChildren(ctx); }
  visitDiTemplateTypeParameter(ctx: DiTemplateTypeParameterContext): void { this.visitChildren(ctx); }
  visitDiTemplateValueParameter(ctx: DiTemplateValueParameterContext): void { this.visitChildren(ctx); }
  visitGenericDiNode(ctx: GenericDiNodeContext): void { this.visitChildren(ctx); }
  visitDiTemplateTypeParameterField(ctx: DiTemplateTypeParameterFieldContext): void { this.visitChildren(ctx); }
  visitDiCompileUnitField(ctx: DiCompileUnitFieldContext): void { this.visitChildren(ctx); }
  visitDiCommonBlockField(ctx: DiCommonBlockFieldContext): void { this.visitChildren(ctx); }
  visitDiBasicTypeField(ctx: DiBasicTypeFieldContext): void { this.visitChildren(ctx); }
  visitGenericDINodeField(ctx: GenericDINodeFieldContext): void { this.visitChildren(ctx); }
  visitTagField(ctx: TagFieldContext): void { this.visitChildren(ctx); }
  visitHeaderField(ctx: HeaderFieldContext): void { this.visitChildren(ctx); }
  visitOperandsField(ctx: OperandsFieldContext): void { this.visitChildren(ctx); }
  visitDiTemplateValueParameterField(ctx: DiTemplateValueParameterFieldContext): void { this.visitChildren(ctx); }
  visitNameField(ctx: NameFieldContext): void { this.visitChildren(ctx); }
  visitTypeField(ctx: TypeFieldContext): void { this.visitChildren(ctx); }
  visitDefaultedField(ctx: DefaultedFieldContext): void { this.visitChildren(ctx); }
  visitValueField(ctx: ValueFieldContext): void { this.visitChildren(ctx); }
  visitMdField(ctx: MdFieldContext): void { this.visitChildren(ctx); }
  visitDiSubroutineTypeField(ctx: DiSubroutineTypeFieldContext): void { this.visitChildren(ctx); }
  visitFlagsField(ctx: FlagsFieldContext): void { this.visitChildren(ctx); }
  visitDiFlags(ctx: DiFlagsContext): void { this.visitChildren(ctx); }
  visitCcField(ctx: CcFieldContext): void { this.visitChildren(ctx); }
  visitAlignField(ctx: AlignFieldContext): void { this.visitChildren(ctx); }
  visitAllocatedField(ctx: AllocatedFieldContext): void { this.visitChildren(ctx); }
  visitAnnotationsField(ctx: AnnotationsFieldContext): void { this.visitChildren(ctx); }
  visitArgField(ctx: ArgFieldContext): void { this.visitChildren(ctx); }
  visitAssociatedField(ctx: AssociatedFieldContext): void { this.visitChildren(ctx); }
  visitAttributesField(ctx: AttributesFieldContext): void { this.visitChildren(ctx); }
  visitBaseTypeField(ctx: BaseTypeFieldContext): void { this.visitChildren(ctx); }
  visitChecksumField(ctx: ChecksumFieldContext): void { this.visitChildren(ctx); }
  visitChecksumkindField(ctx: ChecksumkindFieldContext): void { this.visitChildren(ctx); }
  visitColumnField(ctx: ColumnFieldContext): void { this.visitChildren(ctx); }
  visitConfigMacrosField(ctx: ConfigMacrosFieldContext): void { this.visitChildren(ctx); }
  visitContainingTypeField(ctx: ContainingTypeFieldContext): void { this.visitChildren(ctx); }
  visitCountField(ctx: CountFieldContext): void { this.visitChildren(ctx); }
  visitDebugInfoForProfilingField(ctx: DebugInfoForProfilingFieldContext): void { this.visitChildren(ctx); }
  visitDeclarationField(ctx: DeclarationFieldContext): void { this.visitChildren(ctx); }
  visitDirectoryField(ctx: DirectoryFieldContext): void { this.visitChildren(ctx); }
  visitDiscriminatorField(ctx: DiscriminatorFieldContext): void { this.visitChildren(ctx); }
  visitDataLocationField(ctx: DataLocationFieldContext): void { this.visitChildren(ctx); }
  visitDiscriminatorIntField(ctx: DiscriminatorIntFieldContext): void { this.visitChildren(ctx); }
  visitDwarfAddressSpaceField(ctx: DwarfAddressSpaceFieldContext): void { this.visitChildren(ctx); }
  visitDwoIdField(ctx: DwoIdFieldContext): void { this.visitChildren(ctx); }
  visitElementsField(ctx: ElementsFieldContext): void { this.visitChildren(ctx); }
  visitEmissionKindField(ctx: EmissionKindFieldContext): void { this.visitChildren(ctx); }
  visitEncodingField(ctx: EncodingFieldContext): void { this.visitChildren(ctx); }
  visitEntityField(ctx: EntityFieldContext): void { this.visitChildren(ctx); }
  visitEnumsField(ctx: EnumsFieldContext): void { this.visitChildren(ctx); }
  visitExportSymbolsField(ctx: ExportSymbolsFieldContext): void { this.visitChildren(ctx); }
  visitExprField(ctx: ExprFieldContext): void { this.visitChildren(ctx); }
  visitExtraDataField(ctx: ExtraDataFieldContext): void { this.visitChildren(ctx); }
  visitFileField(ctx: FileFieldContext): void { this.visitChildren(ctx); }
  visitFilenameField(ctx: FilenameFieldContext): void { this.visitChildren(ctx); }
  visitFlagsStringField(ctx: FlagsStringFieldContext): void { this.visitChildren(ctx); }
  visitGetterField(ctx: GetterFieldContext): void { this.visitChildren(ctx); }
  visitGlobalsField(ctx: GlobalsFieldContext): void { this.visitChildren(ctx); }
  visitIdentifierField(ctx: IdentifierFieldContext): void { this.visitChildren(ctx); }
  visitImportsField(ctx: ImportsFieldContext): void { this.visitChildren(ctx); }
  visitIncludePathField(ctx: IncludePathFieldContext): void { this.visitChildren(ctx); }
  visitInlinedAtField(ctx: InlinedAtFieldContext): void { this.visitChildren(ctx); }
  visitIsDeclField(ctx: IsDeclFieldContext): void { this.visitChildren(ctx); }
  visitIsDefinitionField(ctx: IsDefinitionFieldContext): void { this.visitChildren(ctx); }
  visitIsImplicitCodeField(ctx: IsImplicitCodeFieldContext): void { this.visitChildren(ctx); }
  visitIsLocalField(ctx: IsLocalFieldContext): void { this.visitChildren(ctx); }
  visitIsOptimizedField(ctx: IsOptimizedFieldContext): void { this.visitChildren(ctx); }
  visitIsUnsignedField(ctx: IsUnsignedFieldContext): void { this.visitChildren(ctx); }
  visitApiNotesField(ctx: ApiNotesFieldContext): void { this.visitChildren(ctx); }
  visitLanguageField(ctx: LanguageFieldContext): void { this.visitChildren(ctx); }
  visitLineField(ctx: LineFieldContext): void { this.visitChildren(ctx); }
  visitLinkageNameField(ctx: LinkageNameFieldContext): void { this.visitChildren(ctx); }
  visitLowerBoundField(ctx: LowerBoundFieldContext): void { this.visitChildren(ctx); }
  visitMacrosField(ctx: MacrosFieldContext): void { this.visitChildren(ctx); }
  visitNameTableKindField(ctx: NameTableKindFieldContext): void { this.visitChildren(ctx); }
  visitNodesField(ctx: NodesFieldContext): void { this.visitChildren(ctx); }
  visitOffsetField(ctx: OffsetFieldContext): void { this.visitChildren(ctx); }
  visitProducerField(ctx: ProducerFieldContext): void { this.visitChildren(ctx); }
  visitRangesBaseAddressField(ctx: RangesBaseAddressFieldContext): void { this.visitChildren(ctx); }
  visitRankField(ctx: RankFieldContext): void { this.visitChildren(ctx); }
  visitRetainedNodesField(ctx: RetainedNodesFieldContext): void { this.visitChildren(ctx); }
  visitRetainedTypesField(ctx: RetainedTypesFieldContext): void { this.visitChildren(ctx); }
  visitRuntimeLangField(ctx: RuntimeLangFieldContext): void { this.visitChildren(ctx); }
  visitRuntimeVersionField(ctx: RuntimeVersionFieldContext): void { this.visitChildren(ctx); }
  visitScopeField(ctx: ScopeFieldContext): void { this.visitChildren(ctx); }
  visitScopeLineField(ctx: ScopeLineFieldContext): void { this.visitChildren(ctx); }
  visitSdkField(ctx: SdkFieldContext): void { this.visitChildren(ctx); }
  visitSetterField(ctx: SetterFieldContext): void { this.visitChildren(ctx); }
  visitSizeField(ctx: SizeFieldContext): void { this.visitChildren(ctx); }
  visitSourceField(ctx: SourceFieldContext): void { this.visitChildren(ctx); }
  visitSpFlagsField(ctx: SpFlagsFieldContext): void { this.visitChildren(ctx); }
  visitSplitDebugFilenameField(ctx: SplitDebugFilenameFieldContext): void { this.visitChildren(ctx); }
  visitSplitDebugInliningField(ctx: SplitDebugInliningFieldContext): void { this.visitChildren(ctx); }
  visitStrideField(ctx: StrideFieldContext): void { this.visitChildren(ctx); }
  visitStringLengthField(ctx: StringLengthFieldContext): void { this.visitChildren(ctx); }
  visitStringLengthExpressionField(ctx: StringLengthExpressionFieldContext): void { this.visitChildren(ctx); }
  visitStringLocationExpressionField(ctx: StringLocationExpressionFieldContext): void { this.visitChildren(ctx); }
  visitSysrootField(ctx: SysrootFieldContext): void { this.visitChildren(ctx); }
  visitTargetFuncNameField(ctx: TargetFuncNameFieldContext): void { this.visitChildren(ctx); }
  visitTemplateParamsField(ctx: TemplateParamsFieldContext): void { this.visitChildren(ctx); }
  visitThisAdjustmentField(ctx: ThisAdjustmentFieldContext): void { this.visitChildren(ctx); }
  visitThrownTypesField(ctx: ThrownTypesFieldContext): void { this.visitChildren(ctx); }
  visitTypeMacinfoField(ctx: TypeMacinfoFieldContext): void { this.visitChildren(ctx); }
  visitTypesField(ctx: TypesFieldContext): void { this.visitChildren(ctx); }
  visitUnitField(ctx: UnitFieldContext): void { this.visitChildren(ctx); }
  visitUpperBoundField(ctx: UpperBoundFieldContext): void { this.visitChildren(ctx); }
  visitValueIntField(ctx: ValueIntFieldContext): void { this.visitChildren(ctx); }
  visitValueStringField(ctx: ValueStringFieldContext): void { this.visitChildren(ctx); }
  visitVarField(ctx: VarFieldContext): void { this.visitChildren(ctx); }
  visitVirtualIndexField(ctx: VirtualIndexFieldContext): void { this.visitChildren(ctx); }
  visitVirtualityField(ctx: VirtualityFieldContext): void { this.visitChildren(ctx); }
  visitVtableHolderField(ctx: VtableHolderFieldContext): void { this.visitChildren(ctx); }
  
  
  visit(tree: ParseTree): void {
    tree.accept(this);
  }
  visitChildren(node: RuleNode): void {
    for(let i=0; i<node.childCount; i++) node.getChild(i).accept(this);
  }
  visitTerminal(node: TerminalNode): void {
    throw new Error('method not implement');
  }
  visitErrorNode(node: ErrorNode): void {
    this.visitTerminal(node);
  }
  
}

